### ISSUE TITLE
Platform configs should include expected power state for flashing

### ISSUE THREAD

**Issue by mkopec** [Dasharo/osfv-scripts#15]
Platforms need to be in a certain state for flashing. Platform configs should reflect that.

Platform configs should specify a power state for flashing: OFF (power completely removed), G3 (mechanical off, power still provided), S5 (soft off). The RTE should control the platform (sonoff, relay, power button, SPI voltage etc) based on those inputs.

**Comment by macpijan** [comment]
@mkopec 

Currently, we have `init_on` flag which indicates whether the power should be applied: https://github.com/Dasharo/osfv-scripts/blob/main/osfv_cli/osfv_cli/models/V1210.yml#L13

By default it is not applied: https://github.com/Dasharo/osfv-scripts/blob/main/osfv_cli/osfv_cli/rte.py#L197

Do you suggest that we should instead rename this option to `power state` and provide 3 options (OFF, G3, S5), which will drive the power sequencing as needed?

**Comment by macpijan** [comment]
Please see the referenced PR if that is what you need.
