### ISSUE TITLE
snipeit.py doesn't show user names

### ISSUE THREAD

**Issue by krystian-hebel** [Dasharo/osfv-scripts#2]
Output doesn't show which user checked out a given asset. Without that information, it is impossible to ping the user that forgot to check the asset in, or ask that user when the platform will be available.

It also would be nice to have a command to list all platforms checked out by current user, as and end-of-day "have I forgot anything" reminder.

**Comment by macpijan** [comment]
Example output of:  `osfv_cli snipeit list_used`

```
Asset Tag: msi_z690_3, Asset ID: 296, Name: mac, Serial: XXXXXXXXXXXX
Assigned to: Maciej Pijanowski
Lab location: R3/5
RTE IP: XXXXXXXXXX
RTE cpuid: XXXXXXXXXX
RTE Rev: v1.1.0
RTE MAC address: XXXXXXXX
Sonoff IP: XXXXXXXX
PiKVM IP: XXXXXXXX
PiKVM HW Base: 
```

**Comment by macpijan** [comment]
Ad.2 `osfv_cli snipeit list_my`

```
Asset Tag: Protectli VP2410_1, Asset ID: 317, Name: , Serial: 
Assigned to: Maciej Pijanowski
Lab location: 
RTE IP: 192.168.10.233
RTE cpuid: 
RTE Rev: 
RTE MAC address: 02:42:66:1f:90:13
Sonoff IP: 
PiKVM IP: 
PiKVM HW Base: 

Asset Tag: NovaCustom NV40MB 1, Asset ID: 309, Name: , Serial: NKNV40MB0001I00004
Assigned to: Maciej Pijanowski

Asset Tag: msi_z690_3, Asset ID: 296, Name: mac, Serial: 07D2511_LA1E360456
Assigned to: Maciej Pijanowski
Lab location: R3/5
RTE IP: 192.168.10.188
RTE cpuid: 02c0014266f49b55
RTE Rev: v1.1.0
RTE MAC address: 02:42:66:f4:9b:55
Sonoff IP: 192.168.10.69
PiKVM IP: 192.168.10.45
PiKVM HW Base: 
```

**Comment by krystian-hebel** [comment]
@macpijan thanks. New features mostly work, just few minor issues:

- README lists commands as `osfv_cli list_used`, not `osfv_cli snipeit list_used`
- with no assets checked out, `osfv_cli snipeit list_my` shows `No unused assets found`, I think it should be `No used assets` instead
- some users are listed as `Name Surname`, some `Surname Name` - I guess this is a problem with database and not the tool itself

**Comment by macpijan** [comment]
@krystian-hebel I have applied your suggestions here: https://github.com/Dasharo/osfv-scripts/pull/10/files

The last point on names, is rather not tool related. I cannot see such a problem on the new Snipe-IT instance.

**Comment by macpijan** [comment]
@krystian-hebel if you have some time, I would appreciate it if you could take a look.

**Comment by krystian-hebel** [comment]
I thought I closed it already, it is better now, thanks.
