### ISSUE TITLE
Please enable adding options to flashrom

### ISSUE THREAD

**Issue by PLangowski** [Dasharo/osfv-scripts#24]
I think it's a good idea to enble the user to specify options when flashing the DUT with `osfv_cli`. I was recently trying to flash a platform, but flashrom detected multiple chips and made me add the `-c <chip>` option to the command. I ended up modifying the `rte.py` script. It would be nice to be able to do it from CLI.

**Comment by macpijan** [comment]
If this is only about chip name, take a look at other configs and documentation. This is already possible. Please contribute necessary change here: https://github.com/Dasharo/osfv-scripts/pull/22

Adding support for arbitrary arguments might still be a valid reason, if we find a use-case for that.

**Comment by PLangowski** [comment]
I pushed the change.

**Comment by macpijan** [comment]
Then you may close this issue, as long as it resolves your problem.
