### ISSUE TITLE
No support for non-RTE, internally flashed platforms, eg. laptops

### ISSUE THREAD

**Issue by filipleple** [Dasharo/osfv-scripts#49]
Currently, when adding a new model, there is no option to specify that the platform **doesn't have an RTE** and that flashing should be carried out by connecting directly to the DUT and using the **internal programmer**. This is crucial, now that we're integrating the osfv-scripts into OSFV regression testing.

**Comment by macpijan** [comment]
Ok, can you elaborate? Which features of this tool do you aim to use in your particular case?
What was the exact problem when trying to use the tests after integration?

**Comment by filipleple** [comment]
When running a test suite, it checks with osfv_cli first to see if the device is supported, if it's not it fails instantly. But yeah, on second thought we definitely should rather skip the check for laptops than enable adding platforms that couldn't even utilize the tool

**Comment by macpijan** [comment]
Maybe not skip, just document for laptops (if no test stand is applied) we set the snipeit to NO?

**Comment by filipleple** [comment]
Having set `${POWER_CTRL}=     none` and `${SNIPEIT}=      no`  I still get 

```
==============================================================================
Bios-Lock
==============================================================================
BLS001.001 BIOS lock support (Ubuntu) :: BIOS lock is a method to ... | FAIL |
Parent suite setup failed:
Initializing library 'osfv.rf.rte_robot.RobotRTE' with arguments [ 192.168.4.55 | F
alse | config=novacustom-v540tu ] failed: UnsupportedDUTModel: The novacustom-v540t
u model has no counterpart in osfv_cli
Traceback (most recent call last):
  File "/home/flewinski/workstation/fixes/open-source-firmware-validation/robot-ven
v/lib/python3.11/site-packages/osfv/rf/rte_robot.py", line 51, in __init__
    self.rte = RTE(rte_ip, self.cli_model_from_osfv(config), self.sonoff)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flewinski/workstation/fixes/open-source-firmware-validation/robot-ven
v/lib/python3.11/site-packages/osfv/rf/rte_robot.py", line 61, in cli_model_from_os
fv
    raise UnsupportedDUTModel(
osfv.libs.rte.UnsupportedDUTModel: The novacustom-v540tu model has no counterpart i
n osfv_cli
```
Figuring out why right now.
