### ISSUE TITLE
Add OSFV functionality to Check In all devices assigned to you

### ISSUE THREAD

**Issue by dawidlesiak** [Dasharo/osfv-scripts#52]
Add OSFV functionality to Check In all devices assigned to you in SnipeIt

We can create a new category in SnipeIt specifically for employee laptops and update the osfv-scripts to verify if an item is assigned in this category.

**Comment by philipandag** [comment]
https://github.com/Dasharo/osfv-scripts/compare/add-checkin-my-subcommand?expand=1
